spring:
  datasource:
    password: nouhaila
    username: postgres
    url: jdbc:postgresql://172.22.0.2:5432/projet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: conteneurisation
